/*
 * Portfolio Tracker
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AssetCreate {
    #[serde(rename = "symbol")]
    pub symbol: String,
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "type")]
    pub r#type: String,
    #[serde(rename = "exchange_id")]
    pub exchange_id: i32,
    #[serde(rename = "yahoo_ticker", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub yahoo_ticker: Option<Option<String>>,
    #[serde(rename = "coingecko_id", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub coingecko_id: Option<Option<String>>,
}

impl AssetCreate {
    pub fn new(symbol: String, name: String, r#type: String, exchange_id: i32) -> AssetCreate {
        AssetCreate {
            symbol,
            name,
            r#type,
            exchange_id,
            yahoo_ticker: None,
            coingecko_id: None,
        }
    }
}

