/*
 * Portfolio Tracker
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AssetUpdate {
    #[serde(rename = "symbol", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub symbol: Option<Option<String>>,
    #[serde(rename = "name", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub name: Option<Option<String>>,
    #[serde(rename = "type", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub r#type: Option<Option<String>>,
    #[serde(rename = "exchange_id", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub exchange_id: Option<Option<i32>>,
    #[serde(rename = "yahoo_ticker", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub yahoo_ticker: Option<Option<String>>,
    #[serde(rename = "coingecko_id", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub coingecko_id: Option<Option<String>>,
}

impl AssetUpdate {
    pub fn new() -> AssetUpdate {
        AssetUpdate {
            symbol: None,
            name: None,
            r#type: None,
            exchange_id: None,
            yahoo_ticker: None,
            coingecko_id: None,
        }
    }
}

