/*
 * Portfolio Tracker
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct SecretSet {
    #[serde(rename = "value")]
    pub value: String,
}

impl SecretSet {
    pub fn new(value: String) -> SecretSet {
        SecretSet {
            value,
        }
    }
}

