/*
 * Portfolio Tracker
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct TransactionUpdate {
    #[serde(rename = "date", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub date: Option<Option<String>>,
    #[serde(rename = "type", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub r#type: Option<Option<String>>,
    #[serde(rename = "units", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub units: Option<Option<f64>>,
    #[serde(rename = "eur_amount", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub eur_amount: Option<Option<f64>>,
    #[serde(rename = "notes", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub notes: Option<Option<String>>,
}

impl TransactionUpdate {
    pub fn new() -> TransactionUpdate {
        TransactionUpdate {
            date: None,
            r#type: None,
            units: None,
            eur_amount: None,
            notes: None,
        }
    }
}

