/*
 * Portfolio Tracker
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct TransactionCreate {
    #[serde(rename = "asset_id")]
    pub asset_id: i32,
    #[serde(rename = "date")]
    pub date: String,
    #[serde(rename = "type")]
    pub r#type: String,
    #[serde(rename = "units")]
    pub units: f64,
    #[serde(rename = "eur_amount")]
    pub eur_amount: f64,
    #[serde(rename = "notes", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub notes: Option<Option<String>>,
}

impl TransactionCreate {
    pub fn new(asset_id: i32, date: String, r#type: String, units: f64, eur_amount: f64) -> TransactionCreate {
        TransactionCreate {
            asset_id,
            date,
            r#type,
            units,
            eur_amount,
            notes: None,
        }
    }
}

