/*
 * Portfolio Tracker
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// WindowStateRequest : Request model for window state control.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct WindowStateRequest {
    #[serde(rename = "action")]
    pub action: String,
}

impl WindowStateRequest {
    /// Request model for window state control.
    pub fn new(action: String) -> WindowStateRequest {
        WindowStateRequest {
            action,
        }
    }
}

