// This file is auto-generated by @hey-api/openapi-ts

export const AssetCreateSchema = {
  properties: {
    symbol: {
      type: "string",
      maxLength: 50,
      minLength: 1,
      title: "Symbol",
    },
    name: {
      type: "string",
      maxLength: 255,
      minLength: 1,
      title: "Name",
    },
    type: {
      type: "string",
      title: "Type",
    },
    exchange_id: {
      type: "integer",
      title: "Exchange Id",
    },
    yahoo_ticker: {
      anyOf: [
        {
          type: "string",
        },
        {
          type: "null",
        },
      ],
      title: "Yahoo Ticker",
    },
    coingecko_id: {
      anyOf: [
        {
          type: "string",
        },
        {
          type: "null",
        },
      ],
      title: "Coingecko Id",
    },
  },
  type: "object",
  required: ["symbol", "name", "type", "exchange_id"],
  title: "AssetCreate",
} as const;

export const AssetUpdateSchema = {
  properties: {
    symbol: {
      anyOf: [
        {
          type: "string",
        },
        {
          type: "null",
        },
      ],
      title: "Symbol",
    },
    name: {
      anyOf: [
        {
          type: "string",
        },
        {
          type: "null",
        },
      ],
      title: "Name",
    },
    type: {
      anyOf: [
        {
          type: "string",
        },
        {
          type: "null",
        },
      ],
      title: "Type",
    },
    exchange_id: {
      anyOf: [
        {
          type: "integer",
        },
        {
          type: "null",
        },
      ],
      title: "Exchange Id",
    },
    yahoo_ticker: {
      anyOf: [
        {
          type: "string",
        },
        {
          type: "null",
        },
      ],
      title: "Yahoo Ticker",
    },
    coingecko_id: {
      anyOf: [
        {
          type: "string",
        },
        {
          type: "null",
        },
      ],
      title: "Coingecko Id",
    },
  },
  type: "object",
  title: "AssetUpdate",
} as const;

export const ExchangeCreateSchema = {
  properties: {
    name: {
      type: "string",
      maxLength: 255,
      minLength: 1,
      title: "Name",
    },
    type: {
      type: "string",
      title: "Type",
    },
  },
  type: "object",
  required: ["name", "type"],
  title: "ExchangeCreate",
} as const;

export const HTTPValidationErrorSchema = {
  properties: {
    detail: {
      items: {
        $ref: "#/components/schemas/ValidationError",
      },
      type: "array",
      title: "Detail",
    },
  },
  type: "object",
  title: "HTTPValidationError",
} as const;

export const SecretSetSchema = {
  properties: {
    value: {
      type: "string",
      title: "Value",
    },
  },
  type: "object",
  required: ["value"],
  title: "SecretSet",
} as const;

export const TransactionCreateSchema = {
  properties: {
    asset_id: {
      type: "integer",
      title: "Asset Id",
    },
    date: {
      type: "string",
      title: "Date",
    },
    type: {
      type: "string",
      title: "Type",
    },
    units: {
      type: "number",
      title: "Units",
    },
    eur_amount: {
      type: "number",
      title: "Eur Amount",
    },
    notes: {
      anyOf: [
        {
          type: "string",
        },
        {
          type: "null",
        },
      ],
      title: "Notes",
    },
  },
  type: "object",
  required: ["asset_id", "date", "type", "units", "eur_amount"],
  title: "TransactionCreate",
} as const;

export const TransactionUpdateSchema = {
  properties: {
    date: {
      anyOf: [
        {
          type: "string",
        },
        {
          type: "null",
        },
      ],
      title: "Date",
    },
    type: {
      anyOf: [
        {
          type: "string",
        },
        {
          type: "null",
        },
      ],
      title: "Type",
    },
    units: {
      anyOf: [
        {
          type: "number",
        },
        {
          type: "null",
        },
      ],
      title: "Units",
    },
    eur_amount: {
      anyOf: [
        {
          type: "number",
        },
        {
          type: "null",
        },
      ],
      title: "Eur Amount",
    },
    notes: {
      anyOf: [
        {
          type: "string",
        },
        {
          type: "null",
        },
      ],
      title: "Notes",
    },
  },
  type: "object",
  title: "TransactionUpdate",
} as const;

export const ValidationErrorSchema = {
  properties: {
    loc: {
      items: {
        anyOf: [
          {
            type: "string",
          },
          {
            type: "integer",
          },
        ],
      },
      type: "array",
      title: "Location",
    },
    msg: {
      type: "string",
      title: "Message",
    },
    type: {
      type: "string",
      title: "Error Type",
    },
  },
  type: "object",
  required: ["loc", "msg", "type"],
  title: "ValidationError",
} as const;

export const WindowStateRequestSchema = {
  properties: {
    action: {
      type: "string",
      title: "Action",
    },
  },
  type: "object",
  required: ["action"],
  title: "WindowStateRequest",
  description: "Request model for window state control.",
} as const;
