// This file is auto-generated by @hey-api/openapi-ts

export const AssetCreateSchema = {
  properties: {
    symbol: {
      type: "string",
      maxLength: 50,
      minLength: 1,
      title: "Symbol",
    },
    name: {
      type: "string",
      maxLength: 255,
      minLength: 1,
      title: "Name",
    },
    type: {
      type: "string",
      enum: ["crypto", "etf", "cash", "stock"],
      title: "Type",
    },
    exchange_id: {
      anyOf: [
        {
          type: "integer",
        },
        {
          type: "null",
        },
      ],
      title: "Exchange Id",
    },
    yahoo_ticker: {
      anyOf: [
        {
          type: "string",
          maxLength: 50,
        },
        {
          type: "null",
        },
      ],
      title: "Yahoo Ticker",
    },
    coingecko_id: {
      anyOf: [
        {
          type: "string",
          maxLength: 100,
        },
        {
          type: "null",
        },
      ],
      title: "Coingecko Id",
    },
  },
  type: "object",
  required: ["symbol", "name", "type"],
  title: "AssetCreate",
} as const;

export const AssetUpdateSchema = {
  properties: {
    symbol: {
      anyOf: [
        {
          type: "string",
          maxLength: 50,
          minLength: 1,
        },
        {
          type: "null",
        },
      ],
      title: "Symbol",
    },
    name: {
      anyOf: [
        {
          type: "string",
          maxLength: 255,
          minLength: 1,
        },
        {
          type: "null",
        },
      ],
      title: "Name",
    },
    type: {
      anyOf: [
        {
          type: "string",
          enum: ["crypto", "etf", "cash", "stock"],
        },
        {
          type: "null",
        },
      ],
      title: "Type",
    },
    exchange_id: {
      anyOf: [
        {
          type: "integer",
        },
        {
          type: "null",
        },
      ],
      title: "Exchange Id",
    },
    yahoo_ticker: {
      anyOf: [
        {
          type: "string",
          maxLength: 50,
        },
        {
          type: "null",
        },
      ],
      title: "Yahoo Ticker",
    },
    coingecko_id: {
      anyOf: [
        {
          type: "string",
          maxLength: 100,
        },
        {
          type: "null",
        },
      ],
      title: "Coingecko Id",
    },
  },
  type: "object",
  title: "AssetUpdate",
} as const;

export const ExchangeCreateSchema = {
  properties: {
    name: {
      type: "string",
      maxLength: 255,
      minLength: 1,
      title: "Name",
    },
    type: {
      type: "string",
      enum: ["crypto", "broker", "manual"],
      title: "Type",
    },
  },
  type: "object",
  required: ["name", "type"],
  title: "ExchangeCreate",
} as const;

export const HTTPValidationErrorSchema = {
  properties: {
    detail: {
      items: {
        $ref: "#/components/schemas/ValidationError",
      },
      type: "array",
      title: "Detail",
    },
  },
  type: "object",
  title: "HTTPValidationError",
} as const;

export const SettingsResponseSchema = {
  properties: {
    preferences: {
      anyOf: [
        {
          additionalProperties: true,
          type: "object",
        },
        {
          type: "null",
        },
      ],
      title: "Preferences",
    },
    strategy: {
      anyOf: [
        {
          additionalProperties: true,
          type: "object",
        },
        {
          type: "null",
        },
      ],
      title: "Strategy",
    },
  },
  type: "object",
  title: "SettingsResponse",
} as const;

export const TransactionCreateSchema = {
  properties: {
    asset_id: {
      type: "integer",
      title: "Asset Id",
    },
    date: {
      type: "string",
      pattern: "^\\d{4}-\\d{2}-\\d{2}$",
      title: "Date",
    },
    type: {
      type: "string",
      enum: ["buy", "sell", "move"],
      title: "Type",
    },
    units: {
      type: "number",
      title: "Units",
    },
    eur_amount: {
      type: "number",
      title: "Eur Amount",
    },
    notes: {
      anyOf: [
        {
          type: "string",
        },
        {
          type: "null",
        },
      ],
      title: "Notes",
    },
    venue: {
      anyOf: [
        {
          type: "string",
          maxLength: 100,
          minLength: 1,
        },
        {
          type: "null",
        },
      ],
      title: "Venue",
    },
    to_venue: {
      anyOf: [
        {
          type: "string",
          maxLength: 100,
          minLength: 1,
        },
        {
          type: "null",
        },
      ],
      title: "To Venue",
    },
  },
  type: "object",
  required: ["asset_id", "date", "type", "units", "eur_amount"],
  title: "TransactionCreate",
} as const;

export const TransactionUpdateSchema = {
  properties: {
    date: {
      anyOf: [
        {
          type: "string",
          pattern: "^\\d{4}-\\d{2}-\\d{2}$",
        },
        {
          type: "null",
        },
      ],
      title: "Date",
    },
    type: {
      anyOf: [
        {
          type: "string",
          enum: ["buy", "sell", "move"],
        },
        {
          type: "null",
        },
      ],
      title: "Type",
    },
    units: {
      anyOf: [
        {
          type: "number",
        },
        {
          type: "null",
        },
      ],
      title: "Units",
    },
    eur_amount: {
      anyOf: [
        {
          type: "number",
        },
        {
          type: "null",
        },
      ],
      title: "Eur Amount",
    },
    notes: {
      anyOf: [
        {
          type: "string",
        },
        {
          type: "null",
        },
      ],
      title: "Notes",
    },
    venue: {
      anyOf: [
        {
          type: "string",
          maxLength: 100,
          minLength: 1,
        },
        {
          type: "null",
        },
      ],
      title: "Venue",
    },
    to_venue: {
      anyOf: [
        {
          type: "string",
          maxLength: 100,
          minLength: 1,
        },
        {
          type: "null",
        },
      ],
      title: "To Venue",
    },
  },
  type: "object",
  title: "TransactionUpdate",
} as const;

export const ValidationErrorSchema = {
  properties: {
    loc: {
      items: {
        anyOf: [
          {
            type: "string",
          },
          {
            type: "integer",
          },
        ],
      },
      type: "array",
      title: "Location",
    },
    msg: {
      type: "string",
      title: "Message",
    },
    type: {
      type: "string",
      title: "Error Type",
    },
  },
  type: "object",
  required: ["loc", "msg", "type"],
  title: "ValidationError",
} as const;

export const VenueRenameSchema = {
  properties: {
    from_name: {
      type: "string",
      maxLength: 100,
      minLength: 1,
      title: "From Name",
    },
    to_name: {
      type: "string",
      maxLength: 100,
      minLength: 1,
      title: "To Name",
    },
  },
  type: "object",
  required: ["from_name", "to_name"],
  title: "VenueRename",
} as const;
