// This file is auto-generated by @hey-api/openapi-ts

import type { CancelablePromise } from "./core/CancelablePromise";
import { OpenAPI } from "./core/OpenAPI";
import { request as __request } from "./core/request";
import type {
  AssetsListAssetsResponse,
  AssetsCreateAssetData,
  AssetsCreateAssetResponse,
  AssetsGetAssetData,
  AssetsGetAssetResponse,
  AssetsUpdateAssetData,
  AssetsUpdateAssetResponse,
  AssetsDeleteAssetData,
  AssetsDeleteAssetResponse,
  RootResponse,
  HealthCheckResponse,
  ExchangesListExchangesResponse,
  ExchangesCreateExchangeData,
  ExchangesCreateExchangeResponse,
  ExchangesDeleteExchangeData,
  ExchangesDeleteExchangeResponse,
  ExportExportDbResponse,
  MeGetMeResponse,
  NetWorthGetNetWorthData,
  NetWorthGetNetWorthResponse,
  PositionsGetPositionsResponse,
  PositionsGetPositionHistoryData,
  PositionsGetPositionHistoryResponse,
  PricesRefreshPricesData,
  PricesRefreshPricesResponse,
  PricesGetBtcDailyResponse,
  TransactionsCreateTransactionData,
  TransactionsCreateTransactionResponse,
  TransactionsListTransactionsData,
  TransactionsListTransactionsResponse,
  TransactionsUpdateTransactionData,
  TransactionsUpdateTransactionResponse,
  TransactionsDeleteTransactionData,
  TransactionsDeleteTransactionResponse,
} from "./types.gen";

export class AssetsService {
  /**
   * List Assets
   * @returns unknown Successful Response
   * @throws ApiError
   */
  public static listAssets(): CancelablePromise<AssetsListAssetsResponse> {
    return __request(OpenAPI, {
      method: "GET",
      url: "/api/v1/assets/",
    });
  }

  /**
   * Create Asset
   * @param data The data for the request.
   * @param data.requestBody
   * @returns unknown Successful Response
   * @throws ApiError
   */
  public static createAsset(
    data: AssetsCreateAssetData,
  ): CancelablePromise<AssetsCreateAssetResponse> {
    return __request(OpenAPI, {
      method: "POST",
      url: "/api/v1/assets/",
      body: data.requestBody,
      mediaType: "application/json",
      errors: {
        422: "Validation Error",
      },
    });
  }

  /**
   * Get Asset
   * @param data The data for the request.
   * @param data.assetId
   * @returns unknown Successful Response
   * @throws ApiError
   */
  public static getAsset(
    data: AssetsGetAssetData,
  ): CancelablePromise<AssetsGetAssetResponse> {
    return __request(OpenAPI, {
      method: "GET",
      url: "/api/v1/assets/{asset_id}",
      path: {
        asset_id: data.assetId,
      },
      errors: {
        422: "Validation Error",
      },
    });
  }

  /**
   * Update Asset
   * @param data The data for the request.
   * @param data.assetId
   * @param data.requestBody
   * @returns unknown Successful Response
   * @throws ApiError
   */
  public static updateAsset(
    data: AssetsUpdateAssetData,
  ): CancelablePromise<AssetsUpdateAssetResponse> {
    return __request(OpenAPI, {
      method: "PUT",
      url: "/api/v1/assets/{asset_id}",
      path: {
        asset_id: data.assetId,
      },
      body: data.requestBody,
      mediaType: "application/json",
      errors: {
        422: "Validation Error",
      },
    });
  }

  /**
   * Delete Asset
   * Delete a position outright, with its transactions, cached prices and snapshots.
   * @param data The data for the request.
   * @param data.assetId
   * @returns unknown Successful Response
   * @throws ApiError
   */
  public static deleteAsset(
    data: AssetsDeleteAssetData,
  ): CancelablePromise<AssetsDeleteAssetResponse> {
    return __request(OpenAPI, {
      method: "DELETE",
      url: "/api/v1/assets/{asset_id}",
      path: {
        asset_id: data.assetId,
      },
      errors: {
        422: "Validation Error",
      },
    });
  }
}

export class DefaultService {
  /**
   * Root
   * Unauthenticated. Reachable directly on the private network, so it says nothing.
   * @returns unknown Successful Response
   * @throws ApiError
   */
  public static root(): CancelablePromise<RootResponse> {
    return __request(OpenAPI, {
      method: "GET",
      url: "/",
    });
  }

  /**
   * Health Check
   * Health check for Railway. Unauthenticated: the platform probes it without a proxy.
   * @returns unknown Successful Response
   * @throws ApiError
   */
  public static healthCheck(): CancelablePromise<HealthCheckResponse> {
    return __request(OpenAPI, {
      method: "GET",
      url: "/api/health",
    });
  }
}

export class ExchangesService {
  /**
   * List Exchanges
   * @returns unknown Successful Response
   * @throws ApiError
   */
  public static listExchanges(): CancelablePromise<ExchangesListExchangesResponse> {
    return __request(OpenAPI, {
      method: "GET",
      url: "/api/v1/exchanges/",
    });
  }

  /**
   * Create Exchange
   * @param data The data for the request.
   * @param data.requestBody
   * @returns unknown Successful Response
   * @throws ApiError
   */
  public static createExchange(
    data: ExchangesCreateExchangeData,
  ): CancelablePromise<ExchangesCreateExchangeResponse> {
    return __request(OpenAPI, {
      method: "POST",
      url: "/api/v1/exchanges/",
      body: data.requestBody,
      mediaType: "application/json",
      errors: {
        422: "Validation Error",
      },
    });
  }

  /**
   * Delete Exchange
   * @param data The data for the request.
   * @param data.exchangeId
   * @returns unknown Successful Response
   * @throws ApiError
   */
  public static deleteExchange(
    data: ExchangesDeleteExchangeData,
  ): CancelablePromise<ExchangesDeleteExchangeResponse> {
    return __request(OpenAPI, {
      method: "DELETE",
      url: "/api/v1/exchanges/{exchange_id}",
      path: {
        exchange_id: data.exchangeId,
      },
      errors: {
        422: "Validation Error",
      },
    });
  }
}

export class ExportService {
  /**
   * Export Db
   * Download the whole ledger as JSON.
   *
   * The desktop build handed over the SQLite file itself, which is not a thing a hosted
   * Postgres deployment has. Soft-deleted transactions are included on purpose: this is
   * a backup, and dropping them would make the export lossy.
   * @returns unknown Successful Response
   * @throws ApiError
   */
  public static exportDb(): CancelablePromise<ExportExportDbResponse> {
    return __request(OpenAPI, {
      method: "GET",
      url: "/api/v1/export/",
    });
  }
}

export class MeService {
  /**
   * Get Me
   * Who the proxy says is calling, so the SPA can show the account and a sign-out link.
   * @returns unknown Successful Response
   * @throws ApiError
   */
  public static getMe(): CancelablePromise<MeGetMeResponse> {
    return __request(OpenAPI, {
      method: "GET",
      url: "/api/v1/me/",
    });
  }
}

export class NetWorthService {
  /**
   * Get Net Worth
   * @param data The data for the request.
   * @param data.period
   * @returns unknown Successful Response
   * @throws ApiError
   */
  public static getNetWorth(
    data: NetWorthGetNetWorthData = {},
  ): CancelablePromise<NetWorthGetNetWorthResponse> {
    return __request(OpenAPI, {
      method: "GET",
      url: "/api/v1/net-worth/",
      query: {
        period: data.period,
      },
      errors: {
        422: "Validation Error",
      },
    });
  }
}

export class PositionsService {
  /**
   * Get Positions
   * @returns unknown Successful Response
   * @throws ApiError
   */
  public static getPositions(): CancelablePromise<PositionsGetPositionsResponse> {
    return __request(OpenAPI, {
      method: "GET",
      url: "/api/v1/positions/",
    });
  }

  /**
   * Get Position History
   * The value series behind one position's chart.
   *
   * Mirrors /net-worth: the same three granularities, the same fallback on an
   * unknown period, and an empty list rather than a 404 for an asset with no
   * snapshots yet — the chart renders its own empty state.
   * @param data The data for the request.
   * @param data.assetId
   * @param data.period
   * @returns unknown Successful Response
   * @throws ApiError
   */
  public static getPositionHistory(
    data: PositionsGetPositionHistoryData,
  ): CancelablePromise<PositionsGetPositionHistoryResponse> {
    return __request(OpenAPI, {
      method: "GET",
      url: "/api/v1/positions/{asset_id}/history",
      path: {
        asset_id: data.assetId,
      },
      query: {
        period: data.period,
      },
      errors: {
        422: "Validation Error",
      },
    });
  }
}

export class PricesService {
  /**
   * Refresh Prices
   * Pull live quotes unless another process did so recently or is doing so now.
   *
   * The throttle is shared through Postgres (see app/services/refresh.py), so it
   * holds across workers, replicas and the scheduled job.
   * @param data The data for the request.
   * @param data.force Bypass the routine cooldown. For an explicit user-initiated refresh.
   * @returns unknown Successful Response
   * @throws ApiError
   */
  public static refreshPrices(
    data: PricesRefreshPricesData = {},
  ): CancelablePromise<PricesRefreshPricesResponse> {
    return __request(OpenAPI, {
      method: "POST",
      url: "/api/v1/prices/refresh",
      query: {
        force: data.force,
      },
      errors: {
        422: "Validation Error",
      },
    });
  }

  /**
   * Get Btc Daily
   * The last year of daily BTC closes in EUR, oldest first, as cached.
   *
   * Returned as stored, gaps and all: the strategy view decides how far a close
   * may be carried forward, and refuses to compute a regime over a real hole.
   * Empty when the portfolio holds no BTC.
   * @returns unknown Successful Response
   * @throws ApiError
   */
  public static getBtcDaily(): CancelablePromise<PricesGetBtcDailyResponse> {
    return __request(OpenAPI, {
      method: "GET",
      url: "/api/v1/prices/btc/daily",
    });
  }
}

export class TransactionsService {
  /**
   * Create Transaction
   * @param data The data for the request.
   * @param data.requestBody
   * @returns unknown Successful Response
   * @throws ApiError
   */
  public static createTransaction(
    data: TransactionsCreateTransactionData,
  ): CancelablePromise<TransactionsCreateTransactionResponse> {
    return __request(OpenAPI, {
      method: "POST",
      url: "/api/v1/transactions/",
      body: data.requestBody,
      mediaType: "application/json",
      errors: {
        422: "Validation Error",
      },
    });
  }

  /**
   * List Transactions
   * @param data The data for the request.
   * @param data.assetId
   * @returns unknown Successful Response
   * @throws ApiError
   */
  public static listTransactions(
    data: TransactionsListTransactionsData,
  ): CancelablePromise<TransactionsListTransactionsResponse> {
    return __request(OpenAPI, {
      method: "GET",
      url: "/api/v1/transactions/{asset_id}",
      path: {
        asset_id: data.assetId,
      },
      errors: {
        422: "Validation Error",
      },
    });
  }

  /**
   * Update Transaction
   * @param data The data for the request.
   * @param data.txId
   * @param data.requestBody
   * @returns unknown Successful Response
   * @throws ApiError
   */
  public static updateTransaction(
    data: TransactionsUpdateTransactionData,
  ): CancelablePromise<TransactionsUpdateTransactionResponse> {
    return __request(OpenAPI, {
      method: "PUT",
      url: "/api/v1/transactions/{tx_id}/update",
      path: {
        tx_id: data.txId,
      },
      body: data.requestBody,
      mediaType: "application/json",
      errors: {
        422: "Validation Error",
      },
    });
  }

  /**
   * Delete Transaction
   * @param data The data for the request.
   * @param data.txId
   * @returns unknown Successful Response
   * @throws ApiError
   */
  public static deleteTransaction(
    data: TransactionsDeleteTransactionData,
  ): CancelablePromise<TransactionsDeleteTransactionResponse> {
    return __request(OpenAPI, {
      method: "DELETE",
      url: "/api/v1/transactions/{tx_id}/delete",
      path: {
        tx_id: data.txId,
      },
      errors: {
        422: "Validation Error",
      },
    });
  }
}
