// This file is auto-generated by @hey-api/openapi-ts

import type { CancelablePromise } from "./core/CancelablePromise";
import { OpenAPI } from "./core/OpenAPI";
import { request as __request } from "./core/request";
import type {
  ListAssetsApiAssetsGetResponse,
  CreateAssetApiAssetsPostData,
  CreateAssetApiAssetsPostResponse,
  GetAssetApiAssetsAssetIdGetData,
  GetAssetApiAssetsAssetIdGetResponse,
  UpdateAssetApiAssetsAssetIdPutData,
  UpdateAssetApiAssetsAssetIdPutResponse,
  RootGetResponse,
  ListExchangesApiExchangesGetResponse,
  CreateExchangeApiExchangesPostData,
  CreateExchangeApiExchangesPostResponse,
  DeleteExchangeApiExchangesExchangeIdDeleteData,
  DeleteExchangeApiExchangesExchangeIdDeleteResponse,
  ExportDbApiExportGetResponse,
  GetNetWorthApiNetWorthGetData,
  GetNetWorthApiNetWorthGetResponse,
  GetPositionsApiPositionsGetResponse,
  RefreshPricesApiPricesRefreshPostResponse,
  SetSecretApiSecretsNamePostData,
  SetSecretApiSecretsNamePostResponse,
  DeleteSecretApiSecretsNameDeleteData,
  DeleteSecretApiSecretsNameDeleteResponse,
  CreateTransactionApiTransactionsPostData,
  CreateTransactionApiTransactionsPostResponse,
  ListTransactionsApiTransactionsAssetIdGetData,
  ListTransactionsApiTransactionsAssetIdGetResponse,
  UpdateTransactionApiTransactionsTxIdUpdatePutData,
  UpdateTransactionApiTransactionsTxIdUpdatePutResponse,
  DeleteTransactionApiTransactionsTxIdDeleteDeleteData,
  DeleteTransactionApiTransactionsTxIdDeleteDeleteResponse,
  WindowHealthCheckApiHealthGetResponse,
  ToggleWindowStateApiWindowPostData,
  ToggleWindowStateApiWindowPostResponse,
} from "./types.gen";

export class AssetsService {
  /**
   * List Assets
   * @returns unknown Successful Response
   * @throws ApiError
   */
  public static listAssetsApiAssetsGet(): CancelablePromise<ListAssetsApiAssetsGetResponse> {
    return __request(OpenAPI, {
      method: "GET",
      url: "/api/assets/",
    });
  }

  /**
   * Create Asset
   * @param data The data for the request.
   * @param data.requestBody
   * @returns unknown Successful Response
   * @throws ApiError
   */
  public static createAssetApiAssetsPost(
    data: CreateAssetApiAssetsPostData,
  ): CancelablePromise<CreateAssetApiAssetsPostResponse> {
    return __request(OpenAPI, {
      method: "POST",
      url: "/api/assets/",
      body: data.requestBody,
      mediaType: "application/json",
      errors: {
        422: "Validation Error",
      },
    });
  }

  /**
   * Get Asset
   * @param data The data for the request.
   * @param data.assetId
   * @returns unknown Successful Response
   * @throws ApiError
   */
  public static getAssetApiAssetsAssetIdGet(
    data: GetAssetApiAssetsAssetIdGetData,
  ): CancelablePromise<GetAssetApiAssetsAssetIdGetResponse> {
    return __request(OpenAPI, {
      method: "GET",
      url: "/api/assets/{asset_id}",
      path: {
        asset_id: data.assetId,
      },
      errors: {
        422: "Validation Error",
      },
    });
  }

  /**
   * Update Asset
   * @param data The data for the request.
   * @param data.assetId
   * @param data.requestBody
   * @returns unknown Successful Response
   * @throws ApiError
   */
  public static updateAssetApiAssetsAssetIdPut(
    data: UpdateAssetApiAssetsAssetIdPutData,
  ): CancelablePromise<UpdateAssetApiAssetsAssetIdPutResponse> {
    return __request(OpenAPI, {
      method: "PUT",
      url: "/api/assets/{asset_id}",
      path: {
        asset_id: data.assetId,
      },
      body: data.requestBody,
      mediaType: "application/json",
      errors: {
        422: "Validation Error",
      },
    });
  }
}

export class DefaultService {
  /**
   * Root
   * Root endpoint - basic info.
   * @returns unknown Successful Response
   * @throws ApiError
   */
  public static rootGet(): CancelablePromise<RootGetResponse> {
    return __request(OpenAPI, {
      method: "GET",
      url: "/",
    });
  }
}

export class ExchangesService {
  /**
   * List Exchanges
   * @returns unknown Successful Response
   * @throws ApiError
   */
  public static listExchangesApiExchangesGet(): CancelablePromise<ListExchangesApiExchangesGetResponse> {
    return __request(OpenAPI, {
      method: "GET",
      url: "/api/exchanges/",
    });
  }

  /**
   * Create Exchange
   * @param data The data for the request.
   * @param data.requestBody
   * @returns unknown Successful Response
   * @throws ApiError
   */
  public static createExchangeApiExchangesPost(
    data: CreateExchangeApiExchangesPostData,
  ): CancelablePromise<CreateExchangeApiExchangesPostResponse> {
    return __request(OpenAPI, {
      method: "POST",
      url: "/api/exchanges/",
      body: data.requestBody,
      mediaType: "application/json",
      errors: {
        422: "Validation Error",
      },
    });
  }

  /**
   * Delete Exchange
   * @param data The data for the request.
   * @param data.exchangeId
   * @returns unknown Successful Response
   * @throws ApiError
   */
  public static deleteExchangeApiExchangesExchangeIdDelete(
    data: DeleteExchangeApiExchangesExchangeIdDeleteData,
  ): CancelablePromise<DeleteExchangeApiExchangesExchangeIdDeleteResponse> {
    return __request(OpenAPI, {
      method: "DELETE",
      url: "/api/exchanges/{exchange_id}",
      path: {
        exchange_id: data.exchangeId,
      },
      errors: {
        422: "Validation Error",
      },
    });
  }
}

export class ExportService {
  /**
   * Export Db
   * @returns unknown Successful Response
   * @throws ApiError
   */
  public static dbApiExportGet(): CancelablePromise<ExportDbApiExportGetResponse> {
    return __request(OpenAPI, {
      method: "GET",
      url: "/api/export/",
    });
  }
}

export class NetWorthService {
  /**
   * Get Net Worth
   * @param data The data for the request.
   * @param data.period
   * @returns unknown Successful Response
   * @throws ApiError
   */
  public static getNetWorthApiNetWorthGet(
    data: GetNetWorthApiNetWorthGetData = {},
  ): CancelablePromise<GetNetWorthApiNetWorthGetResponse> {
    return __request(OpenAPI, {
      method: "GET",
      url: "/api/net-worth/",
      query: {
        period: data.period,
      },
      errors: {
        422: "Validation Error",
      },
    });
  }
}

export class PositionsService {
  /**
   * Get Positions
   * @returns unknown Successful Response
   * @throws ApiError
   */
  public static getPositionsApiPositionsGet(): CancelablePromise<GetPositionsApiPositionsGetResponse> {
    return __request(OpenAPI, {
      method: "GET",
      url: "/api/positions/",
    });
  }
}

export class PricesService {
  /**
   * Refresh Prices
   * @returns unknown Successful Response
   * @throws ApiError
   */
  public static refreshPricesApiPricesRefreshPost(): CancelablePromise<RefreshPricesApiPricesRefreshPostResponse> {
    return __request(OpenAPI, {
      method: "POST",
      url: "/api/prices/refresh",
    });
  }
}

export class SecretsService {
  /**
   * Set Secret
   * @param data The data for the request.
   * @param data.name
   * @param data.requestBody
   * @returns unknown Successful Response
   * @throws ApiError
   */
  public static setSecretApiSecretsNamePost(
    data: SetSecretApiSecretsNamePostData,
  ): CancelablePromise<SetSecretApiSecretsNamePostResponse> {
    return __request(OpenAPI, {
      method: "POST",
      url: "/api/secrets/{name}",
      path: {
        name: data.name,
      },
      body: data.requestBody,
      mediaType: "application/json",
      errors: {
        422: "Validation Error",
      },
    });
  }

  /**
   * Delete Secret
   * @param data The data for the request.
   * @param data.name
   * @returns unknown Successful Response
   * @throws ApiError
   */
  public static deleteSecretApiSecretsNameDelete(
    data: DeleteSecretApiSecretsNameDeleteData,
  ): CancelablePromise<DeleteSecretApiSecretsNameDeleteResponse> {
    return __request(OpenAPI, {
      method: "DELETE",
      url: "/api/secrets/{name}",
      path: {
        name: data.name,
      },
      errors: {
        422: "Validation Error",
      },
    });
  }
}

export class TransactionsService {
  /**
   * Create Transaction
   * @param data The data for the request.
   * @param data.requestBody
   * @returns unknown Successful Response
   * @throws ApiError
   */
  public static createTransactionApiTransactionsPost(
    data: CreateTransactionApiTransactionsPostData,
  ): CancelablePromise<CreateTransactionApiTransactionsPostResponse> {
    return __request(OpenAPI, {
      method: "POST",
      url: "/api/transactions/",
      body: data.requestBody,
      mediaType: "application/json",
      errors: {
        422: "Validation Error",
      },
    });
  }

  /**
   * List Transactions
   * @param data The data for the request.
   * @param data.assetId
   * @returns unknown Successful Response
   * @throws ApiError
   */
  public static listTransactionsApiTransactionsAssetIdGet(
    data: ListTransactionsApiTransactionsAssetIdGetData,
  ): CancelablePromise<ListTransactionsApiTransactionsAssetIdGetResponse> {
    return __request(OpenAPI, {
      method: "GET",
      url: "/api/transactions/{asset_id}",
      path: {
        asset_id: data.assetId,
      },
      errors: {
        422: "Validation Error",
      },
    });
  }

  /**
   * Update Transaction
   * @param data The data for the request.
   * @param data.txId
   * @param data.requestBody
   * @returns unknown Successful Response
   * @throws ApiError
   */
  public static updateTransactionApiTransactionsTxIdUpdatePut(
    data: UpdateTransactionApiTransactionsTxIdUpdatePutData,
  ): CancelablePromise<UpdateTransactionApiTransactionsTxIdUpdatePutResponse> {
    return __request(OpenAPI, {
      method: "PUT",
      url: "/api/transactions/{tx_id}/update",
      path: {
        tx_id: data.txId,
      },
      body: data.requestBody,
      mediaType: "application/json",
      errors: {
        422: "Validation Error",
      },
    });
  }

  /**
   * Delete Transaction
   * @param data The data for the request.
   * @param data.txId
   * @returns unknown Successful Response
   * @throws ApiError
   */
  public static deleteTransactionApiTransactionsTxIdDeleteDelete(
    data: DeleteTransactionApiTransactionsTxIdDeleteDeleteData,
  ): CancelablePromise<DeleteTransactionApiTransactionsTxIdDeleteDeleteResponse> {
    return __request(OpenAPI, {
      method: "DELETE",
      url: "/api/transactions/{tx_id}/delete",
      path: {
        tx_id: data.txId,
      },
      errors: {
        422: "Validation Error",
      },
    });
  }
}

export class WindowService {
  /**
   * Window Health Check
   * Check if the Tauri window socket server is available.
   * @returns string Successful Response
   * @throws ApiError
   */
  public static healthCheckApiHealthGet(): CancelablePromise<WindowHealthCheckApiHealthGetResponse> {
    return __request(OpenAPI, {
      method: "GET",
      url: "/api/health",
    });
  }

  /**
   * Toggle Window State
   * Toggle window maximize/restore state via Unix socket to Tauri.
   *
   * This endpoint communicates with the Rust backend through a Unix socket
   * to control the window state (maximize/restore).
   * @param data The data for the request.
   * @param data.requestBody
   * @returns string Successful Response
   * @throws ApiError
   */
  public static toggleWindowStateApiWindowPost(
    data: ToggleWindowStateApiWindowPostData,
  ): CancelablePromise<ToggleWindowStateApiWindowPostResponse> {
    return __request(OpenAPI, {
      method: "POST",
      url: "/api/window",
      body: data.requestBody,
      mediaType: "application/json",
      errors: {
        422: "Validation Error",
      },
    });
  }
}
