// This file is auto-generated by @hey-api/openapi-ts

import type { CancelablePromise } from "./core/CancelablePromise";
import { OpenAPI } from "./core/OpenAPI";
import { request as __request } from "./core/request";
import type {
  ListAssetsApiAssetsGetResponse,
  CreateAssetApiAssetsPostData,
  CreateAssetApiAssetsPostResponse,
  GetAssetApiAssetsAssetIdGetData,
  GetAssetApiAssetsAssetIdGetResponse,
  UpdateAssetApiAssetsAssetIdPutData,
  UpdateAssetApiAssetsAssetIdPutResponse,
  DeleteAssetApiAssetsAssetIdDeleteData,
  DeleteAssetApiAssetsAssetIdDeleteResponse,
  RootGetResponse,
  HealthCheckApiHealthGetResponse,
  ListExchangesApiExchangesGetResponse,
  CreateExchangeApiExchangesPostData,
  CreateExchangeApiExchangesPostResponse,
  DeleteExchangeApiExchangesExchangeIdDeleteData,
  DeleteExchangeApiExchangesExchangeIdDeleteResponse,
  ExportDbApiExportGetResponse,
  GetMeApiMeGetResponse,
  GetNetWorthApiNetWorthGetData,
  GetNetWorthApiNetWorthGetResponse,
  GetPositionsApiPositionsGetResponse,
  GetPositionHistoryApiPositionsAssetIdHistoryGetData,
  GetPositionHistoryApiPositionsAssetIdHistoryGetResponse,
  RefreshPricesApiPricesRefreshPostData,
  RefreshPricesApiPricesRefreshPostResponse,
  GetBtcDailyApiPricesBtcDailyGetResponse,
  CreateTransactionApiTransactionsPostData,
  CreateTransactionApiTransactionsPostResponse,
  ListTransactionsApiTransactionsAssetIdGetData,
  ListTransactionsApiTransactionsAssetIdGetResponse,
  UpdateTransactionApiTransactionsTxIdUpdatePutData,
  UpdateTransactionApiTransactionsTxIdUpdatePutResponse,
  DeleteTransactionApiTransactionsTxIdDeleteDeleteData,
  DeleteTransactionApiTransactionsTxIdDeleteDeleteResponse,
} from "./types.gen";

export class AssetsService {
  /**
   * List Assets
   * @returns unknown Successful Response
   * @throws ApiError
   */
  public static listAssetsApiAssetsGet(): CancelablePromise<ListAssetsApiAssetsGetResponse> {
    return __request(OpenAPI, {
      method: "GET",
      url: "/api/assets/",
    });
  }

  /**
   * Create Asset
   * @param data The data for the request.
   * @param data.requestBody
   * @returns unknown Successful Response
   * @throws ApiError
   */
  public static createAssetApiAssetsPost(
    data: CreateAssetApiAssetsPostData,
  ): CancelablePromise<CreateAssetApiAssetsPostResponse> {
    return __request(OpenAPI, {
      method: "POST",
      url: "/api/assets/",
      body: data.requestBody,
      mediaType: "application/json",
      errors: {
        422: "Validation Error",
      },
    });
  }

  /**
   * Get Asset
   * @param data The data for the request.
   * @param data.assetId
   * @returns unknown Successful Response
   * @throws ApiError
   */
  public static getAssetApiAssetsAssetIdGet(
    data: GetAssetApiAssetsAssetIdGetData,
  ): CancelablePromise<GetAssetApiAssetsAssetIdGetResponse> {
    return __request(OpenAPI, {
      method: "GET",
      url: "/api/assets/{asset_id}",
      path: {
        asset_id: data.assetId,
      },
      errors: {
        422: "Validation Error",
      },
    });
  }

  /**
   * Update Asset
   * @param data The data for the request.
   * @param data.assetId
   * @param data.requestBody
   * @returns unknown Successful Response
   * @throws ApiError
   */
  public static updateAssetApiAssetsAssetIdPut(
    data: UpdateAssetApiAssetsAssetIdPutData,
  ): CancelablePromise<UpdateAssetApiAssetsAssetIdPutResponse> {
    return __request(OpenAPI, {
      method: "PUT",
      url: "/api/assets/{asset_id}",
      path: {
        asset_id: data.assetId,
      },
      body: data.requestBody,
      mediaType: "application/json",
      errors: {
        422: "Validation Error",
      },
    });
  }

  /**
   * Delete Asset
   * Delete a position outright, with its transactions, cached prices and snapshots.
   * @param data The data for the request.
   * @param data.assetId
   * @returns unknown Successful Response
   * @throws ApiError
   */
  public static deleteAssetApiAssetsAssetIdDelete(
    data: DeleteAssetApiAssetsAssetIdDeleteData,
  ): CancelablePromise<DeleteAssetApiAssetsAssetIdDeleteResponse> {
    return __request(OpenAPI, {
      method: "DELETE",
      url: "/api/assets/{asset_id}",
      path: {
        asset_id: data.assetId,
      },
      errors: {
        422: "Validation Error",
      },
    });
  }
}

export class DefaultService {
  /**
   * Root
   * Unauthenticated. Reachable directly on the private network, so it says nothing.
   * @returns unknown Successful Response
   * @throws ApiError
   */
  public static rootGet(): CancelablePromise<RootGetResponse> {
    return __request(OpenAPI, {
      method: "GET",
      url: "/",
    });
  }

  /**
   * Health Check
   * Health check for Railway. Unauthenticated: the platform probes it without a proxy.
   * @returns unknown Successful Response
   * @throws ApiError
   */
  public static healthCheckApiHealthGet(): CancelablePromise<HealthCheckApiHealthGetResponse> {
    return __request(OpenAPI, {
      method: "GET",
      url: "/api/health",
    });
  }
}

export class ExchangesService {
  /**
   * List Exchanges
   * @returns unknown Successful Response
   * @throws ApiError
   */
  public static listExchangesApiExchangesGet(): CancelablePromise<ListExchangesApiExchangesGetResponse> {
    return __request(OpenAPI, {
      method: "GET",
      url: "/api/exchanges/",
    });
  }

  /**
   * Create Exchange
   * @param data The data for the request.
   * @param data.requestBody
   * @returns unknown Successful Response
   * @throws ApiError
   */
  public static createExchangeApiExchangesPost(
    data: CreateExchangeApiExchangesPostData,
  ): CancelablePromise<CreateExchangeApiExchangesPostResponse> {
    return __request(OpenAPI, {
      method: "POST",
      url: "/api/exchanges/",
      body: data.requestBody,
      mediaType: "application/json",
      errors: {
        422: "Validation Error",
      },
    });
  }

  /**
   * Delete Exchange
   * @param data The data for the request.
   * @param data.exchangeId
   * @returns unknown Successful Response
   * @throws ApiError
   */
  public static deleteExchangeApiExchangesExchangeIdDelete(
    data: DeleteExchangeApiExchangesExchangeIdDeleteData,
  ): CancelablePromise<DeleteExchangeApiExchangesExchangeIdDeleteResponse> {
    return __request(OpenAPI, {
      method: "DELETE",
      url: "/api/exchanges/{exchange_id}",
      path: {
        exchange_id: data.exchangeId,
      },
      errors: {
        422: "Validation Error",
      },
    });
  }
}

export class ExportService {
  /**
   * Export Db
   * Download the whole ledger as JSON.
   *
   * The desktop build handed over the SQLite file itself, which is not a thing a hosted
   * Postgres deployment has. Soft-deleted transactions are included on purpose: this is
   * a backup, and dropping them would make the export lossy.
   * @returns unknown Successful Response
   * @throws ApiError
   */
  public static dbApiExportGet(): CancelablePromise<ExportDbApiExportGetResponse> {
    return __request(OpenAPI, {
      method: "GET",
      url: "/api/export/",
    });
  }
}

export class MeService {
  /**
   * Get Me
   * Who the proxy says is calling, so the SPA can show the account and a sign-out link.
   * @returns unknown Successful Response
   * @throws ApiError
   */
  public static getMeApiMeGet(): CancelablePromise<GetMeApiMeGetResponse> {
    return __request(OpenAPI, {
      method: "GET",
      url: "/api/me/",
    });
  }
}

export class NetWorthService {
  /**
   * Get Net Worth
   * @param data The data for the request.
   * @param data.period
   * @returns unknown Successful Response
   * @throws ApiError
   */
  public static getNetWorthApiNetWorthGet(
    data: GetNetWorthApiNetWorthGetData = {},
  ): CancelablePromise<GetNetWorthApiNetWorthGetResponse> {
    return __request(OpenAPI, {
      method: "GET",
      url: "/api/net-worth/",
      query: {
        period: data.period,
      },
      errors: {
        422: "Validation Error",
      },
    });
  }
}

export class PositionsService {
  /**
   * Get Positions
   * @returns unknown Successful Response
   * @throws ApiError
   */
  public static getPositionsApiPositionsGet(): CancelablePromise<GetPositionsApiPositionsGetResponse> {
    return __request(OpenAPI, {
      method: "GET",
      url: "/api/positions/",
    });
  }

  /**
   * Get Position History
   * The value series behind one position's chart.
   *
   * Mirrors /net-worth: the same three granularities, the same fallback on an
   * unknown period, and an empty list rather than a 404 for an asset with no
   * snapshots yet — the chart renders its own empty state.
   * @param data The data for the request.
   * @param data.assetId
   * @param data.period
   * @returns unknown Successful Response
   * @throws ApiError
   */
  public static getPositionHistoryApiPositionsAssetIdHistoryGet(
    data: GetPositionHistoryApiPositionsAssetIdHistoryGetData,
  ): CancelablePromise<GetPositionHistoryApiPositionsAssetIdHistoryGetResponse> {
    return __request(OpenAPI, {
      method: "GET",
      url: "/api/positions/{asset_id}/history",
      path: {
        asset_id: data.assetId,
      },
      query: {
        period: data.period,
      },
      errors: {
        422: "Validation Error",
      },
    });
  }
}

export class PricesService {
  /**
   * Refresh Prices
   * @param data The data for the request.
   * @param data.force Bypass the routine cooldown. For an explicit user-initiated refresh.
   * @returns unknown Successful Response
   * @throws ApiError
   */
  public static refreshPricesApiPricesRefreshPost(
    data: RefreshPricesApiPricesRefreshPostData = {},
  ): CancelablePromise<RefreshPricesApiPricesRefreshPostResponse> {
    return __request(OpenAPI, {
      method: "POST",
      url: "/api/prices/refresh",
      query: {
        force: data.force,
      },
      errors: {
        422: "Validation Error",
      },
    });
  }

  /**
   * Get Btc Daily
   * The last year of daily BTC closes in EUR, oldest first, as cached.
   *
   * Returned as stored, gaps and all: the strategy view decides how far a close
   * may be carried forward, and refuses to compute a regime over a real hole.
   * Empty when the portfolio holds no BTC.
   * @returns unknown Successful Response
   * @throws ApiError
   */
  public static getBtcDailyApiPricesBtcDailyGet(): CancelablePromise<GetBtcDailyApiPricesBtcDailyGetResponse> {
    return __request(OpenAPI, {
      method: "GET",
      url: "/api/prices/btc/daily",
    });
  }
}

export class TransactionsService {
  /**
   * Create Transaction
   * @param data The data for the request.
   * @param data.requestBody
   * @returns unknown Successful Response
   * @throws ApiError
   */
  public static createTransactionApiTransactionsPost(
    data: CreateTransactionApiTransactionsPostData,
  ): CancelablePromise<CreateTransactionApiTransactionsPostResponse> {
    return __request(OpenAPI, {
      method: "POST",
      url: "/api/transactions/",
      body: data.requestBody,
      mediaType: "application/json",
      errors: {
        422: "Validation Error",
      },
    });
  }

  /**
   * List Transactions
   * @param data The data for the request.
   * @param data.assetId
   * @returns unknown Successful Response
   * @throws ApiError
   */
  public static listTransactionsApiTransactionsAssetIdGet(
    data: ListTransactionsApiTransactionsAssetIdGetData,
  ): CancelablePromise<ListTransactionsApiTransactionsAssetIdGetResponse> {
    return __request(OpenAPI, {
      method: "GET",
      url: "/api/transactions/{asset_id}",
      path: {
        asset_id: data.assetId,
      },
      errors: {
        422: "Validation Error",
      },
    });
  }

  /**
   * Update Transaction
   * @param data The data for the request.
   * @param data.txId
   * @param data.requestBody
   * @returns unknown Successful Response
   * @throws ApiError
   */
  public static updateTransactionApiTransactionsTxIdUpdatePut(
    data: UpdateTransactionApiTransactionsTxIdUpdatePutData,
  ): CancelablePromise<UpdateTransactionApiTransactionsTxIdUpdatePutResponse> {
    return __request(OpenAPI, {
      method: "PUT",
      url: "/api/transactions/{tx_id}/update",
      path: {
        tx_id: data.txId,
      },
      body: data.requestBody,
      mediaType: "application/json",
      errors: {
        422: "Validation Error",
      },
    });
  }

  /**
   * Delete Transaction
   * @param data The data for the request.
   * @param data.txId
   * @returns unknown Successful Response
   * @throws ApiError
   */
  public static deleteTransactionApiTransactionsTxIdDeleteDelete(
    data: DeleteTransactionApiTransactionsTxIdDeleteDeleteData,
  ): CancelablePromise<DeleteTransactionApiTransactionsTxIdDeleteDeleteResponse> {
    return __request(OpenAPI, {
      method: "DELETE",
      url: "/api/transactions/{tx_id}/delete",
      path: {
        tx_id: data.txId,
      },
      errors: {
        422: "Validation Error",
      },
    });
  }
}
