// This file is auto-generated by @hey-api/openapi-ts

export type AssetCreate = {
  symbol: string;
  name: string;
  type: string;
  exchange_id: number;
  yahoo_ticker?: string | null;
  coingecko_id?: string | null;
};

export type AssetUpdate = {
  symbol?: string | null;
  name?: string | null;
  type?: string | null;
  exchange_id?: number | null;
  yahoo_ticker?: string | null;
  coingecko_id?: string | null;
};

export type ExchangeCreate = {
  name: string;
  type: string;
};

export type HTTPValidationError = {
  detail?: Array<ValidationError>;
};

export type SecretSet = {
  value: string;
};

export type TransactionCreate = {
  asset_id: number;
  date: string;
  type: string;
  units: number;
  eur_amount: number;
  notes?: string | null;
};

export type TransactionUpdate = {
  date?: string | null;
  type?: string | null;
  units?: number | null;
  eur_amount?: number | null;
  notes?: string | null;
};

export type ValidationError = {
  loc: Array<string | number>;
  msg: string;
  type: string;
};

/**
 * Request model for window state control.
 */
export type WindowStateRequest = {
  action: string;
};

export type ListAssetsApiAssetsGetResponse = {
  [key: string]: unknown;
};

export type CreateAssetApiAssetsPostData = {
  requestBody: AssetCreate;
};

export type CreateAssetApiAssetsPostResponse = {
  [key: string]: unknown;
};

export type GetAssetApiAssetsAssetIdGetData = {
  assetId: number;
};

export type GetAssetApiAssetsAssetIdGetResponse = {
  [key: string]: unknown;
};

export type UpdateAssetApiAssetsAssetIdPutData = {
  assetId: number;
  requestBody: AssetUpdate;
};

export type UpdateAssetApiAssetsAssetIdPutResponse = {
  [key: string]: unknown;
};

export type RootGetResponse = unknown;

export type ListExchangesApiExchangesGetResponse = {
  [key: string]: unknown;
};

export type CreateExchangeApiExchangesPostData = {
  requestBody: ExchangeCreate;
};

export type CreateExchangeApiExchangesPostResponse = {
  [key: string]: unknown;
};

export type DeleteExchangeApiExchangesExchangeIdDeleteData = {
  exchangeId: number;
};

export type DeleteExchangeApiExchangesExchangeIdDeleteResponse = {
  [key: string]: unknown;
};

export type ExportDbApiExportGetResponse = unknown;

export type GetNetWorthApiNetWorthGetData = {
  period?: string;
};

export type GetNetWorthApiNetWorthGetResponse = {
  [key: string]: unknown;
};

export type GetPositionsApiPositionsGetResponse = {
  [key: string]: unknown;
};

export type RefreshPricesApiPricesRefreshPostResponse = {
  [key: string]: unknown;
};

export type SetSecretApiSecretsNamePostData = {
  name: string;
  requestBody: SecretSet;
};

export type SetSecretApiSecretsNamePostResponse = {
  [key: string]: unknown;
};

export type DeleteSecretApiSecretsNameDeleteData = {
  name: string;
};

export type DeleteSecretApiSecretsNameDeleteResponse = {
  [key: string]: unknown;
};

export type CreateTransactionApiTransactionsPostData = {
  requestBody: TransactionCreate;
};

export type CreateTransactionApiTransactionsPostResponse = {
  [key: string]: unknown;
};

export type ListTransactionsApiTransactionsAssetIdGetData = {
  assetId: number;
};

export type ListTransactionsApiTransactionsAssetIdGetResponse = {
  [key: string]: unknown;
};

export type UpdateTransactionApiTransactionsTxIdUpdatePutData = {
  requestBody: TransactionUpdate;
  txId: number;
};

export type UpdateTransactionApiTransactionsTxIdUpdatePutResponse = {
  [key: string]: unknown;
};

export type DeleteTransactionApiTransactionsTxIdDeleteDeleteData = {
  txId: number;
};

export type DeleteTransactionApiTransactionsTxIdDeleteDeleteResponse = {
  [key: string]: unknown;
};

export type WindowHealthCheckApiHealthGetResponse = {
  [key: string]: string;
};

export type ToggleWindowStateApiWindowPostData = {
  requestBody: WindowStateRequest;
};

export type ToggleWindowStateApiWindowPostResponse = {
  [key: string]: string;
};
