// This file is auto-generated by @hey-api/openapi-ts

export type AssetCreate = {
  symbol: string;
  name: string;
  type: "crypto" | "etf" | "cash" | "stock";
  exchange_id: number;
  yahoo_ticker?: string | null;
  coingecko_id?: string | null;
};

export type type = "crypto" | "etf" | "cash" | "stock";

export type AssetUpdate = {
  symbol?: string | null;
  name?: string | null;
  type?: "crypto" | "etf" | "cash" | "stock" | null;
  exchange_id?: number | null;
  yahoo_ticker?: string | null;
  coingecko_id?: string | null;
};

export type ExchangeCreate = {
  name: string;
  type: "crypto" | "broker" | "manual";
};

export type type2 = "crypto" | "broker" | "manual";

export type HTTPValidationError = {
  detail?: Array<ValidationError>;
};

export type TransactionCreate = {
  asset_id: number;
  date: string;
  type: "buy" | "sell";
  units: number;
  eur_amount: number;
  notes?: string | null;
};

export type type3 = "buy" | "sell";

export type TransactionUpdate = {
  date?: string | null;
  type?: "buy" | "sell" | null;
  units?: number | null;
  eur_amount?: number | null;
  notes?: string | null;
};

export type ValidationError = {
  loc: Array<string | number>;
  msg: string;
  type: string;
};

export type AssetsListAssetsResponse = {
  [key: string]: unknown;
};

export type AssetsCreateAssetData = {
  requestBody: AssetCreate;
};

export type AssetsCreateAssetResponse = {
  [key: string]: unknown;
};

export type AssetsGetAssetData = {
  assetId: number;
};

export type AssetsGetAssetResponse = {
  [key: string]: unknown;
};

export type AssetsUpdateAssetData = {
  assetId: number;
  requestBody: AssetUpdate;
};

export type AssetsUpdateAssetResponse = {
  [key: string]: unknown;
};

export type AssetsDeleteAssetData = {
  assetId: number;
};

export type AssetsDeleteAssetResponse = {
  [key: string]: unknown;
};

export type RootResponse = unknown;

export type HealthCheckResponse = unknown;

export type ExchangesListExchangesResponse = {
  [key: string]: unknown;
};

export type ExchangesCreateExchangeData = {
  requestBody: ExchangeCreate;
};

export type ExchangesCreateExchangeResponse = {
  [key: string]: unknown;
};

export type ExchangesDeleteExchangeData = {
  exchangeId: number;
};

export type ExchangesDeleteExchangeResponse = {
  [key: string]: unknown;
};

export type ExportExportDbResponse = unknown;

export type MeGetMeResponse = {
  [key: string]: unknown;
};

export type NetWorthGetNetWorthData = {
  period?: string;
};

export type NetWorthGetNetWorthResponse = {
  [key: string]: unknown;
};

export type PositionsGetPositionsResponse = {
  [key: string]: unknown;
};

export type PositionsGetPositionHistoryData = {
  assetId: number;
  period?: string;
};

export type PositionsGetPositionHistoryResponse = {
  [key: string]: unknown;
};

export type PricesRefreshPricesData = {
  /**
   * Bypass the routine cooldown. For an explicit user-initiated refresh.
   */
  force?: boolean;
};

export type PricesRefreshPricesResponse = {
  [key: string]: unknown;
};

export type PricesGetBtcDailyResponse = {
  [key: string]: unknown;
};

export type TransactionsCreateTransactionData = {
  requestBody: TransactionCreate;
};

export type TransactionsCreateTransactionResponse = {
  [key: string]: unknown;
};

export type TransactionsListTransactionsData = {
  assetId: number;
};

export type TransactionsListTransactionsResponse = {
  [key: string]: unknown;
};

export type TransactionsUpdateTransactionData = {
  requestBody: TransactionUpdate;
  txId: number;
};

export type TransactionsUpdateTransactionResponse = {
  [key: string]: unknown;
};

export type TransactionsDeleteTransactionData = {
  txId: number;
};

export type TransactionsDeleteTransactionResponse = {
  [key: string]: unknown;
};
